### ISSUE TITLE
README specifies wrong Jest package

### ISSUE THREAD

**Issue by jrunning** [babel/babel-jest#12]
The README says:

> Make the following changes to package.json:
> ```
> {
>  "dependencies": {
>    "babel-jest": "*",
>    "jest": "*"
>  },
> ...
> ```

However, "jest" is an [unrelated package](https://www.npmjs.com/package/jest) ("JavaScriptational State Transfer"). The correct package is [jest-cli](https://www.npmjs.com/package/jest-cli).

**Comment by sebmck** [comment]
Thanks!
