### ISSUE TITLE
5.0.1 breaks `jest.dontMock`

### ISSUE THREAD

**Issue by compedit** [babel/babel-jest#16]
Looks like the imports are being hoisted above the `jest.dontMock` call, turning them into mocks. Pretty sure this is due to  babel itself, but figured the issue would be more relevant here.

## [Actual test code](https://github.com/compedit/module-boilerplate/blob/c40fcb87189254ce8f690a51befa780aaef37fa5/src/__tests__/person-test.js)

```js
jest.dontMock('../person');

import Person from '../person';

describe('Person', () => {
  it('should create a new person', () => {
    const person = new Person('somebody');
    expect(person.name).toBe('somebody');
  });

  it('should greet someone', () => {
    const person = new Person('somebody');
    expect(person.greet('someone')).toBe('Hello someone, my name is somebody');
  });
});
```

## (broken) Compiled output using 5.0.1

```js
'use strict';
 
var _interopRequireWildcard = function (obj) { return obj && obj.__esModule ? obj : { 'default': obj }; };
 
var _Person = require('../person');
 
var _Person2 = _interopRequireWildcard(_Person);
 
jest.dontMock('../person');
 
describe('Person', function () {
  it('should create a new person', function () {
    var person = new _Person2['default']('somebody');
    expect(person.name).toBe('somebody');
  });
 
  it('should greet someone', function () {
    var person = new _Person2['default']('somebody');
    expect(person.greet('someone')).toBe('Hello someone, my name is somebody');
  });
});
```

## Compiled output using 4.0.0

```js
"use strict";
 
var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };
 
jest.dontMock("../person");
 
var Person = _interopRequire(require("../person"));
 
describe("Person", function () {
  it("should create a new person", function () {
    var person = new Person("somebody");
    expect(person.name).toBe("somebody");
  });
 
  it("should greet someone", function () {
    var person = new Person("somebody");
    expect(person.greet("someone")).toBe("Hello someone, my name is somebody");
  });
});
```

Entire repo available [here](https://github.com/compedit/module-boilerplate), broken tests are on the [babel-5 branch](https://github.com/compedit/module-boilerplate/tree/c40fcb87189254ce8f690a51befa780aaef37fa5)

**Comment by Munksey** [comment]
I use a custom preprocessing file which also broke after upgrading. This is a good find and it is most definitely related to the hosting of the import statements (which is apart of the ES6 spec).

**Comment by alanrsoares** [comment]
Any solution that doesn't include rolling back do 4.x ?

**Comment by jagandecapri** [comment]
Facing the same problem. Any solution to workaround this?

**Comment by sebmck** [comment]
Seems more like a jest bug to me. It should be running on the output after, not before.

**Comment by sebmck** [comment]
You can just use normal `require`.

**Comment by Kureev** [comment]
@sebmck Could you tell more about it? I just trying to run ES6 + JSX thru babel-jest and got `render() of undefined` error. I think I tried pretty everything: moved from 0.12 -> 0.10.38, latest versions of everything, but seems not to work. Should I put in some code or it's a known issue?
P.S. I've tried to use standard commonjs syntax for require and export, but it moves to `toUpperCase() of undefined`. What's wrong?

**Comment by sebmck** [comment]
@Kureev As in, just using CommonJS modules instead of ES6 ones.

**Comment by Kureev** [comment]
@sebmck I've replaced all `import ... from` constructions to `const ... = require(...)` and `export default ...` to `module.exports = ...`. It moves me to `toUpperCase()` issue. Any suggestions?

**Comment by sebmck** [comment]
No idea what the `toUpperCase` issue is, it's too vague. Do you have a stacktrace?

**Comment by cmmartin** [comment]
The ```toUpperCase``` error sounds like the really bad error message that React throws when you reference a component in jsx that doesn't exist. Switching to ```require``` works for me.

**Comment by nkashyap** [comment]
Any plan for fixing this issue anytime soon???

**Comment by sebmck** [comment]
@nkashyap It's not an issue and can likely be closed. `import`s are hoisted. There is nothing that can be done with that. They're fundamentally incompatible. Continue using `require` if you want this behaviour.

**Comment by compedit** [comment]
@sebmck agreed, closing now if that's cool. [Updated tests to just use `require`](https://github.com/compedit/module-boilerplate/blob/babel-5/src/__tests__/person-test.js) for anyone curious.

**Comment by sasajib** [comment]
I was facing this issue... and found a solution...I think this solution should be here... as I don't want my code base to change with require...and other module.export hack...

```javascript
//spec/point.spec.js
import '../auto_mock_off';
import { Point } from '../point';

//auto_mock_off.js
jest.autoMockOff();
```
Thanks @rauschma [for the repo](https://github.com/rauschma/babel-on-node)

**Comment by juliankrispel** [comment]
@sasajib that's not a solution, that's turning off `autoMock`. If we turn off autoMock we might as well just use something other than jest...

**Comment by jstejada** [comment]
agree with @juliankrispel , looks like using something else is the best option

**Comment by snatesan** [comment]
Another solution is to put dontMock lines to another file and import that in the test code. 
For example
MyTestFileDontMock.js
<code>
  jest.dontMock('../person');
</code>
And in MyTestFile.js
<pre>
<code>
import "./MyTestFileDontMock.js";

import Person from '../person';

...
</code>
</pre>

**Comment by tony-kerz** [comment]
i can't seem to get any of the workarounds to work for this:
`package.json`:
```
  "devDependencies": {
//...
    "babel-jest": "^6.0.1",
    "jest-cli": "^0.8.0",
//...
  },
```
```
  "scripts": {
    "test": "BABEL_JEST_STAGE=0 jest"
  },
```
```
  "jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "testFileExtensions": ["js"],
    "moduleFileExtensions": ["js"],
    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react",
      "<rootDir>/node_modules/react-dom",
      "<rootDir>/node_modules/react-addons-test-utils",
      "<rootDir>/node_modules/fbjs"
    ]
  }
```
`shared.js`:
```
import _ from 'lodash'

export function replace(o, old, nu) {
// ...
}
```
`__tests__/shared-test.js` (version-1):
```
jest.dontMock('../shared')
const replace = require('../shared')

describe('replace', () => {
 it('works for basic case', () => {
   expect(replace({a: 'a'}, 'a', 'b')).toBe({b: 'a'})
 })
})
```
result:
```
SyntaxError: /Users/tony/git/redux-scratch/mock-server/__tests__/shared-test.js: /Users/tony/git/redux-scratch/mock-server/shared.js: Unexpected token import
```
`__tests__/shared-test.js` (version-2):
```
import './shared-test-no'
import replace from '../shared'

describe('replace', () => {
 it('works for basic case', () => {
   expect(replace({a: 'a'}, 'a', 'b')).toBe({b: 'a'})
 })
})
```
`shared-test-no.js`:
```
jest.dontMock('../shared')
```
result:
```
SyntaxError: /Users/tony/git/redux-scratch/mock-server/__tests__/shared-test.js: Unexpected token import
```

can anyone spot my folly?

cheers,
tony.

**Comment by rauschma** [comment]
@tony-kerz Babel runs, but it doesn’t transpile ES6 to ES5. If you want it to do so, you need specify a preset, either via `package.json` or via `.babelrc`: http://www.2ality.com/2015/11/configuring-babel6.html

**Comment by tony-kerz** [comment]
thx @rauschma,

i added a `.babelrc` but no love yet, if you have a moment, here is my branch: 

https://github.com/tony-kerz/redux-scratch/tree/tk/jest

likely something stupid on my part

**Comment by canastro** [comment]
I'm having exactly the same problem as @tony-kerz but only for imports on my dependencies... 
I have .babelrc in both my main module and in my dependency.

**Comment by snatesan** [comment]
@tony-kerz Are you running the tests via command "npm test"

I cloned your repository and made changes to file "mock-server/__tests__/shared-test.js" to uncomment the "import" statements. I did not get the error you were reporting. The second import statement, "import replace from '../shared'", was failing because there was no default export in shared.js

Import statement works when I changes the "mock-server/__tests__/shared-test.js" as follows

```
import './shared-test-no'

// https://github.com/babel/babel-jest/issues/16
import { replace } from '../shared'

describe('replace', () => {
 it('works for basic case', () => {
   expect(replace({a: 'a'}, 'a', 'b')).toBe({b: 'a'})
 })
})
```

**Comment by canastro** [comment]
@snatesan  
Imports will be hoisted and that will "break" any "jest.dontMock" you might want to use. 

https://github.com/babel/babel-jest/issues/16

**Comment by snatesan** [comment]
@canastro, https://github.com/babel/babel-jest/issues/16#issuecomment-155611005 is the workaround for that

**Comment by tony-kerz** [comment]
@snatesan you rock! 

with your help, i verified that the following three patterns work (pick your poison):

---
`shared.js`:
```
export function replace() {/*...*/}
```
`shared-test-no.js`:
```
jest.dontMock('../shared')
```
`shared-test.js`:
```
import './shared-test-no'
import { replace } from '../shared'
```
---
`shared.js`:
```
export function replace() {/*...*/}
```
`shared-test.js`:
```
jest.dontMock('../shared')
const replace = require('../shared').replace
```
---
`shared.js`:
```
export default function replace() {/*...*/}
```
`shared-test.js`:
```
jest.dontMock('../shared')
const replace = require('../shared').default
```

**Comment by canastro** [comment]
I'm getting this "Unexpected token import" only when I do imports to modules of mine that are in node_modules folder. 

babel_jest seems to ignore all files in the node_modules folder, to fix this I had to go to babel-jest/index.js and change to something like this:

```
var babel = require("babel-core");

module.exports = {
  process: function (src, filename) {

    const isMyModule = filename.indexOf("node_modules/my-prefix") !== -1;
    const isNotInNodeModules = filename.indexOf("node_modules") === -1;

    if (!babel.util.canCompile(filename)) {
        return src;
    }

    if (isNotInNodeModules || isAviago) {
        return babel.transform(src, {
            filename: filename,
            retainLines: true
        }).code;
    }

    return src;
  }
};
```

Is there any other way to do this that I might be forgetting?

**Comment by canastro** [comment]
I'm getting this "Unexpected token import" only when I do imports to modules of mine that are in node_modules folder. 

babel_jest seems to ignore all files in the node_modules folder, to fix this I had to go to babel-jest/index.js and change to something like this:

```
var babel = require("babel-core");

module.exports = {
  process: function (src, filename) {

    const isMyModule = filename.indexOf("node_modules/my-prefix") !== -1;
    const isNotInNodeModules = filename.indexOf("node_modules") === -1;

    if (!babel.util.canCompile(filename)) {
        return src;
    }

    if (isNotInNodeModules || isAviago) {
        return babel.transform(src, {
            filename: filename,
            retainLines: true
        }).code;
    }

    return src;
  }
};
```

Is there any other way to do this that I might be forgetting?

**Comment by mikem-mup** [comment]
Can this issue be re-opened? It continues to spawn issues in the repo and we currently only have a workaround, not a solution. Can `dontMock` be refactored to allow for the import hoisting from `babel-jest` so that we can write 'proper' ES6 modules instead of a hybrid `import`+`require` setup?

**Comment by b-gran** [comment]
In case anyone is still looking for an easy fix similar to [this one](16#issuecomment-155611005),
create a filed called dontmock.js with the contents below. Then you can

```
import 'dontmock';
import es6modules from 'your-chosen-modules';

// your jest tests
```

The es6 modules you import will automatically be jest.dontMock() 'ed,
but you will still be able to mock modules you require()

<pre><code>
// dontmock.js
if (jest === null || jest === undefined) {
  throw new Error('jest must be defined.');
}

// Manually dontMock the imports
jest.dontMock('fs');
jest.dontMock('acorn');
jest.dontMock('acorn/dist/walk');
jest.dontMock('path');

// Imports need to be required.
let fs = require('fs');
let acorn = require('acorn');
let walk = require('acorn/dist/walk');
let path = require('path');

// Read the contents of the 'importer' (the file that imported dontmock.js)
var importer = fs.readFileSync(jest.currentTestPath(), 'utf-8');

// Parse the file using acorn
var AST = acorn.parse(importer, { ecmaVersion: 6, sourceType: 'module' });

// Absolute path of the file which imported dontmock
const testPath = path.dirname(jest.currentTestPath());

// Walk the AST of the file for import declarations
// This allows us to dontMock any ES6 imported files, which we know
// will crash jest.
walk.simple(AST, {
  'ImportDeclaration': function (state) {
    // We aren't going to dontMock this file.
    if (state.source.value.match(/dontmock/) !== null) return;

    // dontMock the absolute path of the imported file.
    jest.dontMock(testPath + path.sep + state.source.value);
  },
});
</pre></code>

**Comment by felix-d** [comment]
Another issue.

I have that module

```js
// MyActions.js
import flux from 'flux';

export default flux.createActions({
  myAction() {
    return {
      actionType: 'MY ACTION',
    }
  },
});
```
And that module is used by another module I am testing. MyActions is mocked.

```js
// MyTestedModule.js
import MyActions from './MyActions';
...
MyActions.myAction();
```
And I'm getting the error

`MyActions2.default.myAction is not a function.`

I don't have this error if I replace `export default` by `module.exports =` in `MyActions.js`

Am I doing something wrong here?

**Comment by wgoto-peer** [comment]
If you're test directory paths are analogous to your project files, you can do a replace on the path by using `jest.currentTestPath()`, however if you are using the `--coverage` option, it will not track modules used with `import` statements.
