### ISSUE TITLE
When running tests, errors show wrong line numbers.

### ISSUE THREAD

**Issue by trusktr** [babel/babel-jest#19]
The code being tested is written in ES6 modules. It seems like the jest errors that are shown are relative to the transpiled code, not the original source. How can we fix this problem? Do source maps work with babel-jest somehow?

**Comment by fdubost** [comment]
I have exactly the same problem... Is there any solution ?

**Comment by sebmck** [comment]
I guess I could enable the `retainLines` option once I ship the next minor.
