### ISSUE TITLE
Getting errors when using a polyfill

### ISSUE THREAD

**Issue by nheyn** [babel/babel-jest#20]
I always get an error when trying to use a polyfill. I've tried both "babel/polyfill" and  "es6-shim",  as described in https://github.com/babel/babel-jest/issues/5, and both give different errors.

When using "babel/polyfill" I get:
>Using Jest CLI v0.4.0
> FAIL \__tests\__/dispatcher-test.js
>TypeError: /var/www/\__tests\__/dispatcher-test.js: /var/www/node_modules/babel/polyfill.js: /var/www/node_modules/babel/node_modules/babel-core/polyfill.js: /var/www/node_modules/babel/node_modules/babel-core/lib/babel/polyfill.js: /var/www/node_modules/babel/node_modules/babel-core/node_modules/core-js/shim.js: /var/www/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es5.js: /var/www/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.cof.js: /var/www/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.wks.js: Cannot read property 'g' of undefined
>1 test failed, 0 tests passed (1 total)
>Run time: 2.822s

And for "es6-shim" I get:
>Using Jest CLI v0.4.0
> FAIL \__tests\__/dispatcher-test.js
>TypeError: /var/www/\__tests\__/dispatcher-test.js: /var/www/node_modules/es6-shim/es6-shim.js: Object #\<Map\> has no method 'keys'
>1 test failed, 0 tests passed (1 total)
>Run time: 2.78s

I've completely commented out test code and still get the errors. Here is what is left in /var/www/\__tests\__/dispatcher-test.js:
```
jest.dontMock('es6-shim'); //Or "babel/polyfill"
import 'es6-shim';         //Or "babel/polyfill"

describe('Dispatcher', function() {
	it('registers callbacks', function() {
		/* commented out code */
	});
});
```

**Comment by juliocesar** [comment]
@nheyn For the time being, you can get away with the following steps:

1) Source the [object-assign](https://www.npmjs.com/package/object-assign) package.
2) Do the following:

    import assign from 'object-assign'
    Object.assign = assign

    // …

**Comment by salomvary** [comment]
Another possible solution (at least it helped me with polyfilling Promises):

in `package.json`:
```json
  "jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "setupEnvScriptFile": "<rootDir>/jestEnvironment.js",
    "unmockedModulePathPatterns": ["core-js/.*"]
  }
```

`jestEnvironment.js`:
```js
require.requireActual('babel/polyfill')
```

tests need no polyfill to import:
```js
describe('Something', () => {
    it('does something',() => {
        something()
    })
})
```

**Comment by nheyn** [comment]
@salomvary That works, thanks.

**Comment by atecarlos** [comment]
@salomvary that was very helpful. Thanks!
