### ISSUE TITLE
Writing tests in ES6

### ISSUE THREAD

**Issue by hollandben** [babel/babel-jest#21]
I can get a test running that uses `babel-jest` to preprocessor my ES6 module, but I've noticed that it doesn't run against the test file itself. Is this that case or am I doing something wrong?

**Edit:** It doesn't seem to have a problem with some of the syntax (`let`) but the imports don't appear to be working

**Comment by hollandben** [comment]
Ignore me, it was a setup problem

**Comment by bartonhammond** [comment]
@hollandben What was the 

> setup problem?  

I'm having exact issue w/ RN 0.17
