### ISSUE TITLE
Returned src from process missing line breaks

### ISSUE THREAD

**Issue by omerts** [babel/babel-jest#25]
```javascript
require('./FeedTag.css');

import React from 'react';
import {Paper, FontIcon} from 'material-ui';

var defaultImage = require('./images/avatar-default.png');
```

Output from process:
![image](https://cloud.githubusercontent.com/assets/4996164/7515368/01ce81fe-f4cf-11e4-89f5-dd0af2164b10.png)

It is a problem for me, since I am trying to string away the requires for css and images, since I am using jest which doesn't work with webpack (tried using jest-webpack unsuccessfully).

**Comment by sebmck** [comment]
This is due to #23, otherwise the line numbers will be off since jest doesn't have sourcemap support. Nothing can really be done to *fix* it unfortunately.
