### ISSUE TITLE
ES6 import lowers the branch coverage percentage

### ISSUE THREAD

**Issue by Serfenia** [babel/babel-jest#27]
Hello.

I use Jest for unit testing my React components. For some reason when I import my dependencies using ES6 module syntax it lowers the branch percentage when using `--coverage`. 

When I change:
~~~
import someDependency from 'someDependency';
~~~

To
~~~
var someDependency = require('someDependency');
~~~

The coverage of the branches go up.
Is this an issue of babel-jest or the jest-cli itself?

Regards,
Patrick

**Comment by Crazy50** [comment]
I ran into the same issue myself. Started digging through the lcov file to understand what happens and noticed at line 1, there's 4 branches with 1 not being executed. If you use babel to translate the file, there's the following function added at the top if you use import:
```js
var _interopRequireDefault = function (obj) { return obj && obj.__esModule ? obj : { "default": obj }; };
```
The 4 branches are in that function, which the first part, checking if obj is truthy, is impossible to pass with working code. I tried to find a way to use istanbul's ignore comments, but it always occurs after the _interopRequireDefault function. Still searching for solutions myself, too much of a perfectionist to let "90% branches" slide.

**Comment by sebmck** [comment]
What does Jest use for coverage?

**Comment by Crazy50** [comment]
Jest uses Istanbul. I tried modifying babel-jest to inject /* istanbul ignore next */ for that function, but it wouldn't ignore it. I noticed Babel moved from
```js
function _interopRequireDefault(obj) {return obj && obj.__esModule ? obj : { 'default': obj };}
```
to
```js
var _interopRequireDefault = require("babel-runtime/helpers/interop-require-default")["default"];
```
but for some reason, the transform function that babel-jest calls does not use the require style. The require method is great, because it encapsulates the branches and keeps things at 100%. I see that babel-jest specifies an older babel-core, but the newer one seems to still output the function instead of the require. A hacky way to make it work is to modify the babel-jest/index.js to do:
```js
    if (filename.indexOf("node_modules") === -1 && babel.canCompile(filename)) {
      return babel.transform(src, { filename: filename, stage: stage, retainLines: true }).code.replace
      "function _interopRequireDefault(obj) {return obj && obj.__esModule ? obj : { 'default': obj };}", 'var _interopRequireDefault = require("babel-runtime/helpers/interop-require-default")["default"];');
    }
```

then you must include:
```js
jest.dontMock('babel-runtime/helpers/interop-require-default');
```
at the top of all tests. I'm just not convinced this hack is the right way and there must be some config to babel that will get the correct output. Their test expected outputs use the require, not the function, which leads me to believe there is a way to get transform to ouput the correct format.

**Comment by sebmck** [comment]
@Crazy50 It didn't move to that at all. That's a part of the the [optional `runtime`](http://babeljs.io/docs/usage/runtime/). If it's using Istanbul then it's easy enough to just add `auxiliaryComment`.

**Comment by sebmck** [comment]
Also note that the `babel-core` version specified in `package.json` uses a `^` so the latest version of `babel-core` is installed every time :)

**Comment by sebmck** [comment]
Just pushed out 5.2.1, let me know if that did the trick.

**Comment by Crazy50** [comment]
Not sure what happened with my packages then, oh well. 5.2.1 fixes the problem for me and don't need 
```js
jest.dontMock('babel-runtime/helpers/interop-require-default');
```
in every one of my tests. Thanks!

**Comment by Crazy50** [comment]
Also just figured out where I saw that avatar and the name in the emails. Was just looking at the React-Europe site earlier today saying "I wish I could be in Paris for this..." Thanks for making Babel @sebmck ! I switched over just a couple weeks ago and haven't looked back.

**Comment by sebmck** [comment]
No problem! Awesome to hear! :smile:

**Comment by mbrio** [comment]
Hi, I seem to be having this problem too. I'm using the latest version of babel-jest and jest. For files that have `import mod from './mod` I can not get a higher rating than 75 on branches. I put up a very simple example project: https://github.com/mbrio/babel-jest-coverage-test.

You can see on files with no import it goes up to 100 and on files with import it goes up to 75.

Any help would be greatly appreciated. When I get into the office I was planning on digging into the babel-jest code to see if there is anything I could figure out.
