### ISSUE TITLE
Problem when using object.keys

### ISSUE THREAD

**Issue by MathRobin** [babel/babel-jest#33]
Hi, i get an error when using the Object.keys method. Here an example to make it more easier to reproduce :

    describe('A test', function () {
        it('should do something', function () {
            expect(Object.keys({}).length).toBe(0);
        });
    });

I get this when i run jest via babel-jest :

    TypeError: /var/www/workflow-mailjet/tests/Mailjet.specs.js: /var/www/workflow-mailjet/node_modules/babel-runtime/core-js/object/keys.js: /var/www/workflow-mailjet/node_modules/babel-runtime/node_modules/core-js/library/fn/object/keys.js: /var/www/workflow-mailjet/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.statics-accept-primitives.js: /var/www/workflow-mailjet/node_modules/babel-runtime/node_modules/core-js/library/modules/$.def.js: Cannot read property 'g' of undefined
    at /var/www/workflow-mailjet/node_modules/babel-runtime/node_modules/core-js/library/modules/$.def.js:2:19
    at /var/www/workflow-mailjet/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.statics-accept-primitives.js:2:16
    at /var/www/workflow-mailjet/node_modules/babel-runtime/node_modules/core-js/library/fn/object/keys.js:1:68
    at /var/www/workflow-mailjet/node_modules/babel-runtime/core-js/object/keys.js:1:98
    at /var/www/workflow-mailjet/tests/Mailjet.specs.js:4:33

When I comment this line :

    expect(Object.keys({}).length).toBe(0);

Or replace it by something more simple, like : 

    describe('A test', function () {
        it('should do something', function () {
            expect(0).toBe(0);
        });
    });

All runs correctly. No other tests script.

**Comment by cpojer** [comment]
This shouldn't be happening any more. You might need to unmock babel-runtime in your `unmockedModulePathPatterns`.

**Comment by MathRobin** [comment]
Ok thanks, I'll try asap. Thank again !
