### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by joshhornby** [babel/babel-jest#38]
I am running the following command `BABEL_JEST_STAGE=0 jest`

And getting the following error:

```
const cacheA = testPerformanceCache && testPerformanceCache[a[0]];
^^^^^
SyntaxError: Use of const in strict mode.
```

In `node_modules/jest-cli/src/TestRunner.js:433`

My `package.json` looks like 

```
  "jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react"
    ],
    "testDirectoryName": "unit",
    "testPathDirs": [
      "<rootDir>/app/tests/"
    ]
  },
```

**Comment by sebmck** [comment]
This is an error in `jest` and completely unrelated to `babel-jest` and `babel`. I'd recommend double checking that you're on a compatible version of Node too.

**Comment by walkerrandolphsmith** [comment]
@sebmck can you point me in the right direction to solve this issue with jest? I am running into the same issue and can't seem to resolve it.

**Comment by sebmck** [comment]
You're using an old Node version.

**Comment by walkerrandolphsmith** [comment]
I understand now, thanks.

**Comment by owap** [comment]
@sebmck upgrading to Node 4.1.1 solved my problem (was on v0.12.4).  Thanks!

**Comment by RahulDole** [comment]
I upgraded to 5.0.0 but still the same issue

**Comment by wanderley** [comment]
I updated my node to `v4.2.3` and it solved the issue.

**Comment by coolReactDev** [comment]
I am on version 5.5.0 ans still has this error
C:\DEV\SVN\sam\player2016\trunk\ContentPlayer\node_modules\jest-cli\bin\jest.js:12
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
