### ISSUE TITLE
problem with delete

### ISSUE THREAD

**Issue by seekshiva** [babel/babel-jest#41]
The npm [collections](https://www.npmjs.com/package/collections) package uses delete command to delete key from objects. when I test a module that depends on this package, I get this:

  - SyntaxError: /<project-dir>/index.js: /<project-dir>/node_modules/collections/sorted-map.js: /<project-dir>/node_modules/collections/shim.js: /<project-dir>/node_modules/collections/shim-array.js: /<project-dir>/node_modules/collections/generic-order.js: /<project-dir>/node_modules/collections/shim-object.js: Unexpected token delete

**Comment by cpojer** [comment]
Feel free to reopen if this still persists with `jest-cli@next`.
