### ISSUE TITLE
Do not ignore files from dependencies which have declared browserify babelify transform

### ISSUE THREAD

**Issue by pnuzhdin** [babel/babel-jest#50]
I've forked https://github.com/pnuzhdin/babelify-jest this project to use the subject feature right now. But it will be best to have it in the original babel-jest.

**Comment by robin-barnes-triptease** [comment]
I have this problem too. To clarify, dependencies that have:

```
  "browserify": {
    "transform": [
      "babelify"
    ]
  }
```

in their package.json file do not get bableified when using babel-jest.

**Comment by cpojer** [comment]
Can you provide some more context about what the problem with babel-jest is? I'm going to close this diff until then and will be happy to reopen. Just managing my tasks queue :)
