### ISSUE TITLE
Why did you remove auxiliaryCommentBefore?

### ISSUE THREAD

**Issue by homer0** [babel/babel-jest#51]
Just that. Because of that, for every class I test, I have to do this in order to fix the coverage:

```javascript
expect(() => MyClass()).toThrow('Cannot call a class as a function');
```

Thanks.

**Comment by chromakode** [comment]
Even when hacking `auxiliaryCommentBefore` back in, I haven't had success getting babel-jest to exclude the auto-generated Babel boilerplate. @homer0, did you find a workaround for this?

**Comment by cpojer** [comment]
cc @kittens ?
