### ISSUE TITLE
Where did support for `export module *` go? 

### ISSUE THREAD

**Issue by amir20** [babel/babel-jest#52]
Looks like the latest version breaks `export module` es6 features. As mentioned in https://github.com/facebook/jest/pull/622, `module.exports = *` needs to be used instead. Is this a bug? Why was this dropped?

**Comment by treehau5** [comment]
Are there any updates with this? As many pointed out, those of us who wish to go forward with es6 would like to be able to use es6 export syntax.

**Comment by damiandennis** [comment]
similar issue here, seems that babel-jest is completely broken for es6.

**Comment by ide** [comment]
What probably happened is that Babel fixed a bug in how it implements exports by following the spec, so jest now needs to mimic `import`'s semantics.

**Comment by amir20** [comment]
I should have mentioned that I found a workaround by using https://github.com/59naga/babel-plugin-add-module-exports. It does seem to work.

**Comment by cpojer** [comment]
This will be fixed in 0.9.0 (try `jest-cli@next`). See https://github.com/facebook/jest/pull/741.
